# Generated by Django 5.0.4 on 2024-05-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_admin_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Admin_user',
        ),
    ]
